version: '2'
services:
  db:
    build: ./db
  www:
    depends_on:
      - db
    build: .
    volumes:
      - "./:/var/www/html"
    ports:
      - 89:80
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306    
